# Generated by Django 3.2.5 on 2021-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ml_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(max_length=500)),
                ('accuracy', models.CharField(max_length=500)),
                ('fmeasure', models.CharField(max_length=500)),
                ('precision', models.CharField(max_length=500)),
                ('recall', models.CharField(max_length=500)),
                ('val_tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='preprocessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
